service_user: vault
service_group: vault
package_version: "2.1.1"
package_release: "1"
hashicorp_rpm_gpg_key_url: https://rpm.releases.hashicorp.com/gpg
kms_region: us-east-1
auto_unseal_kms_key_id: alias/vault-ha-dev-auto-unseal
tls_cert_file: /opt/vault/tls/tls.crt
tls_key_file: /opt/vault/tls/tls.key
