---
- name: Install Vault package
  ansible.builtin.import_tasks: install.yml

- name: Create Vault service identity and directories
  ansible.builtin.import_tasks: identity_and_directories.yml

- name: Install Vault TLS files
  ansible.builtin.import_tasks: tls.yml

- name: Configure Vault runtime
  ansible.builtin.import_tasks: runtime.yml